name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: user/app:latest
    - uses: akhileshns/heroku-deploy@v3.12.12 
      with: 
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "xpfarm-tictactoe-api"
        heroku_email: "martin.hablak@gmail.com"
        usedocker: true
